[[constraint]]
  name = "github.com/sdboyer/deptest"
  version = "0.8.0"

[[constraint]]
  name = "github.com/darkowlzz/deptest-project-2"
  branch = "master"

[[constraint]]
  name = "github.com/boltdb/bolt"
  branch = "master"
